### ISSUE TITLE
Timeout is not available in Alpine Linux

### ISSUE THREAD

**Issue by raphaelahrens** [tantSinnister/wait-for-it#1]
@raphaelahrens when I run your script with no timeout setting I kept getting the error: timeout: can't execute '15': No such file or directory 15 being the default TIMEOUT. However, when I used -1 no-timeout it worked?

**Comment by n1b0r** [comment]
I'm facing the same problem, did you find any solution else than setting timeout to -1 ?

**Comment by raphaelahrens** [comment]
The problem is the different syntax of the busybox timeout, which is used by alpine.
You can just replace the `timeout $TIMEOUT` with `timeout -t $TIMEOUT` in line 58, and 60.

The problem is there is no general solution without writing a lot of extra code, while in my opinion it is easier to just change the two lines.

**Comment by n1b0r** [comment]
Thanks for your repply.
After changing the two lines as explained, the wait-for-it.sh script works fine in alpine containers.

Here is my test :
- `nano Dockerfile`

```
FROM alpine:latest

RUN apk update && apk add ca-certificates && update-ca-certificates && apk add openssl

RUN cd / && wget https://raw.githubusercontent.com/raphaelahrens/wait-for-it/master/wait-for-it.sh
RUN chmod a+x /*.sh

RUN sed -i '58s/timeout /timeout -t /' /wait-for-it.sh
RUN sed -i '60s/timeout /timeout -t /' /wait-for-it.sh

CMD sh /wait-for-it.sh www.google.com:80
```
- build it : `docker build -t test .`
- run it :

```
$ docker run --rm test
wait-for-it.sh: waiting 15 seconds for www.google.fr:80
wait-for-it.sh: www.google.com:80 is available after 0 seconds
```
